# Generated by Django 3.1.6 on 2021-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('shirt_story', models.CharField(max_length=50)),
                ('big_story', models.TextField()),
                ('pages_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo', models.URLField()),
            ],
        ),
    ]
