# Generated by Django 3.1.6 on 2021-03-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.AlterField(
            model_name='products',
            name='shirt_story',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
