# Generated by Django 3.1.6 on 2021-03-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210306_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='shirt_story',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='big_story',
            new_name='description',
        ),
    ]
