# Generated by Django 3.1.6 on 2021-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
