# Generated by Django 3.1.6 on 2021-03-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_products_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_d', models.CharField(max_length=20, null=True)),
                ('author_info', models.TextField()),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='post_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
